SELECT * FROM TB_STUDENT;
SELECT * FROM TB_PROFESSOR;

--1.
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT 
ORDER BY 3;

--2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR 
WHERE NOT PROFESSOR_NAME LIKE '___';

--3.
SELECT PROFESSOR_NAME 교수이름,
EXTRACT(YEAR FROM SYSDATE) - (TO_NUMBER(SUBSTR(PROFESSOR_SSN, 1, 2)) + 1900) 나이 
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY 2;

--4.
SELECT SUBSTR(PROFESSOR_NAME, 2) 이름 
FROM TB_PROFESSOR;

--5.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT 
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - 
(TO_NUMBER(SUBSTR(STUDENT_SSN, 1, 2)) + 1900) >= 20;

--6.
SELECT TO_CHAR(TO_DATE('20201225','YYYYMMDD'), 'DAY')
FROM DUAL;

--7.
SELECT TO_CHAR(TO_DATE('99/10/11','YY/MM/DD'), 'YYYY/MM/DD') 첫번째,
       TO_CHAR(TO_DATE('49/10/11','YY/MM/DD'), 'YYYY/MM/DD') 두번째,
       TO_CHAR(TO_DATE('49/10/11','RR/MM/DD'), 'YYYY/MM/DD') 세번째,
       TO_CHAR(TO_DATE('99/10/11','RR/MM/DD'), 'YYYY/MM/DD') 네번째
FROM DUAL;

--8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT 
WHERE NOT STUDENT_NO LIKE 'A%';

--9.
SELECT ROUND(AVG(POINT),1) 평점
FROM TB_GRADE 
WHERE STUDENT_NO = 'A517178';

--10.
SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)"
FROM TB_STUDENT 
GROUP BY DEPARTMENT_NO;

--11.
SELECT COUNT(*) 
FROM TB_STUDENT 
WHERE COACH_PROFESSOR_NO IS NULL;

--12.
SELECT * 
FROM TB_GRADE 
WHERE STUDENT_NO = 'A112113';